// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['cmd']['App']['ClearLogs']();
}

export function DeletePlaylist(arg1) {
  return window['go']['cmd']['App']['DeletePlaylist'](arg1);
}

export function GeneratePlaylist(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['cmd']['App']['GeneratePlaylist'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAllPlaylists() {
  return window['go']['cmd']['App']['GetAllPlaylists']();
}

export function GetAppInfo() {
  return window['go']['cmd']['App']['GetAppInfo']();
}

export function GetConfig() {
  return window['go']['cmd']['App']['GetConfig']();
}

export function GetEnabledSources() {
  return window['go']['cmd']['App']['GetEnabledSources']();
}

export function GetLastParsedAt() {
  return window['go']['cmd']['App']['GetLastParsedAt']();
}

export function GetLogs() {
  return window['go']['cmd']['App']['GetLogs']();
}

export function GetParseStatus() {
  return window['go']['cmd']['App']['GetParseStatus']();
}

export function GetSongCount() {
  return window['go']['cmd']['App']['GetSongCount']();
}

export function GetUniqueArtists() {
  return window['go']['cmd']['App']['GetUniqueArtists']();
}

export function GetUniqueGenres() {
  return window['go']['cmd']['App']['GetUniqueGenres']();
}

export function ParseDatabase(arg1) {
  return window['go']['cmd']['App']['ParseDatabase'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['cmd']['App']['SaveConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['cmd']['App']['SelectDirectory']();
}

export function SetLastFMCredentials(arg1, arg2, arg3) {
  return window['go']['cmd']['App']['SetLastFMCredentials'](arg1, arg2, arg3);
}

export function SetMusicBrainzCredentials(arg1, arg2) {
  return window['go']['cmd']['App']['SetMusicBrainzCredentials'](arg1, arg2);
}

export function SetRockboxPath(arg1) {
  return window['go']['cmd']['App']['SetRockboxPath'](arg1);
}

export function SetSpotifyCredentials(arg1, arg2, arg3) {
  return window['go']['cmd']['App']['SetSpotifyCredentials'](arg1, arg2, arg3);
}

export function WipeData() {
  return window['go']['cmd']['App']['WipeData']();
}
