// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs():Promise<void>;

export function DeletePlaylist(arg1:number):Promise<void>;

export function GeneratePlaylist(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<any>;

export function GetAllPlaylists():Promise<any>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetConfig():Promise<any>;

export function GetEnabledSources():Promise<Array<string>>;

export function GetLastParsedAt():Promise<any>;

export function GetLogs():Promise<any>;

export function GetParseStatus():Promise<any>;

export function GetSongCount():Promise<number>;

export function GetUniqueArtists():Promise<Array<string>>;

export function GetUniqueGenres():Promise<Array<string>>;

export function ParseDatabase(arg1:boolean):Promise<void>;

export function SaveConfig(arg1:Record<string, any>):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetLastFMCredentials(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetMusicBrainzCredentials(arg1:string,arg2:boolean):Promise<void>;

export function SetRockboxPath(arg1:string):Promise<void>;

export function SetSpotifyCredentials(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function WipeData():Promise<void>;
